# 대여소(공공자전거 거치대) 데이터를 살펴보고, 필요한 데이터만 추출하여 저장.

2023년 6월 기준 대여소 데이터 활용.

<b> 대여소 번호, 대여소명, 상세주소, 위도, 경도 등의 정보를 확인할 수 있다. </b>

2023년 1월~6월 사이에 40개의 대여소가 새롭게 설치되었다.

자치구별 대여소는 송파구(218), 강서구(189), 강남구(171) 순으로 많은 것을 확인하였다.

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt

In [13]:
# UnicodeDecodeError: 'utf-8' 해결
office = pd.read_csv("rentaloffice(2306).csv", encoding='cp949')

In [14]:
office.head()

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식
0,301,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07,20.0,20.0,QR
1,302,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07,12.0,12.0,QR
2,303,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07,8.0,8.0,QR
3,305,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978332,2015-01-07,16.0,16.0,QR
4,307,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100,2015-10-07,11.0,11.0,QR

In [16]:
office.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2749 entries, 0 to 2748
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   대여소번호   2749 non-null   int64
 1   대여소명    2749 non-null   object
 2   자치구     2749 non-null   object
 3   상세주소    2749 non-null   object
 4   위도      2749 non-null   float64
 5   경도      2749 non-null   float64
 6   설치시기    2749 non-null   object
 7   LCD     1315 non-null   float64
 8   QR      1582 non-null   float64
 9   운영방식    2749 non-null   object
dtypes: float64(4), int64(1), object(5)
memory usage: 214.9+ KB

In [39]:
# 분석에 사용할 컬럼엔 결측치 없음 
office.isnull().sum()

대여소번호       0
대여소명        0
자치구         0
상세주소        0
위도          0
경도          0
설치시기        0
LCD      1434
QR       1167
운영방식        0
dtype: int64

In [18]:
office['설치시기'] = pd.to_datetime(office['설치시기'])

In [21]:
office.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2749 entries, 0 to 2748
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   대여소번호   2749 non-null   int64
 1   대여소명    2749 non-null   object
 2   자치구     2749 non-null   object
 3   상세주소    2749 non-null   object
 4   위도      2749 non-null   float64
 5   경도      2749 non-null   float64
 6   설치시기    2749 non-null   datetime64[ns]
 7   LCD     1315 non-null   float64
 8   QR      1582 non-null   float64
 9   운영방식    2749 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 214.9+ KB

In [27]:
office.sort_values(by='설치시기', ascending=False)

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식
1703,3933,오류동부골든아파트 후문 옆,구로구,구로구 고척로 49,37.499382,126.841141,2023-05-30,NaN,10.0,QR
1936,5867,H타워 앞,영등포구,영등포구 버드나루로15,37.520241,126.912453,2023-05-23,NaN,10.0,QR
1781,3988,메종에떼르넬 101동 앞,금천구,금천구 독산동 336-26,37.470947,126.887711,2023-05-23,NaN,5.0,QR
779,3726,삼양동사거리,강북구,강북구 삼양로 163-1,37.617928,127.021362,2023-05-17,NaN,6.0,QR
636,4842,면목라온프라이빗 아파트,중랑구,중랑구 면목동197-4,37.582676,127.077660,2023-05-16,NaN,12.0,QR
...,...,...,...,...,...,...,...,...,...,...
1175,106,합정역 7번출구 앞,마포구,서울특별시 마포구 독막로 4,37.548645,126.912826,2015-09-06,NaN,12.0,QR
1173,104,합정역 1번출구 앞,마포구,서울특별시 마포구 양화로 59,37.550629,126.914986,2015-09-06,NaN,13.0,QR
1172,103,망원역 2번출구 앞,마포구,서울특별시 마포구 월드컵로 79,37.554951,126.910835,2015-09-06,NaN,14.0,QR
1174,105,합정역 5번출구 앞,마포구,서울특별시 마포구 양화로 48,37.550007,126.914825,2015-09-06,NaN,5.0,QR
3,305,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978332,2015-01-07,16.0,16.0,QR

In [29]:
# 올해 이후에 40개의 대여소가 새롭게 설치되었다.
office[office['설치시기']>'2023-01-01'].count()

대여소번호    40
대여소명     40
자치구      40
상세주소     40
위도       40
경도       40
설치시기     40
LCD       0
QR       40
운영방식     40
dtype: int64

In [34]:
# 송파구, 강서구, 강남구 순으로 거치대가 많은 것을 볼 수 있다.
office['자치구'].value_counts()

송파구     218
강서구     189
강남구     171
영등포구    155
서초구     148
노원구     136
강동구     122
마포구     120
구로구     114
양천구     112
종로구     103
은평구      98
중랑구      93
성동구      92
용산구      91
중구       88
광진구      86
동대문구     84
성북구      82
서대문구     81
관악구      79
도봉구      76
금천구      76
동작구      74
강북구      61
Name: 자치구, dtype: int64

In [32]:
# 분석에 필요한 열만 추출
office_data = office[['대여소번호', '대여소명', '자치구', '상세주소', '위도', '경도']]

In [33]:
office_data

,대여소번호,대여소명,자치구,상세주소,위도,경도
0,301,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451
1,302,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060
2,303,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663
3,305,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978332
4,307,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100
...,...,...,...,...,...,...
2744,3699,상일파출소 옆,강동구,강동구 상일동 520-1,37.556553,127.165878
2745,3700,강변그대가리버뷰 입구 맞은편,강동구,강동구 천호동 250-7,37.548164,127.122574
2746,3701,방아삼거리,강동구,강동구 둔촌동 118-2,37.523281,127.146133
2747,4951,강동농협 버스정류소 앞(광채빌라),강동구,강동구 암사동 488-21,37.547966,127.135162
2748,4952,천호시장 버스정류소 옆,강동구,강동구 천호동 397-465,37.541466,127.130257

In [37]:
# 한글 깨짐 방지 코드 encoding='cp949'
office_data.to_csv('office_data.csv', index=False, encoding='cp949')